--liquibase formatted sql
--changeset josgeary:release_227.1.01_ODS_ADOBE_ETL_AC_CAMPAIGNOFFER_MODIFY_COLUMN_DATATYPE_ROLLBACK.sql runAlways:false
--preconditions onFail:HALT onError:HALT

/*****************************************************************************************************************
*  File name:01_ODS_ADOBE_ETL_AC_CAMPAIGNOFFER_MODIFY_COLUMN_DATATYPE_ROLLBACK.sql
*  Purpose: To modify column datatype.
*  Prerequisites:                                                            
*  1. Login as SYSTEM/SYS
*  History
*  When               Who                           What
*  09/23/2024         Capgemini                     Initial Draft		                                                     
******************************************************************************************************************/

/*===============================*/
/* Action: BACKUP the table      */
/*===============================*/

CREATE TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.AC_CAMPAIGNOFFER_BLD;
CREATE TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.AC_CAMPAIGNOFFER_SWP;
CREATE TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.AC_CAMPAIGNOFFER_STG;
COMMIT;

/*========================================*/
/* Action: Alter the column datatype      */
/*========================================*/

ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD ADD PROPOSITION_ID_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD ADD INTERACTION_ID_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP ADD PROPOSITION_ID_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP ADD INTERACTION_ID_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG ADD PROPOSITION_ID_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG ADD INTERACTION_ID_NEW VARCHAR2(255);
COMMIT;

UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET PROPOSITION_ID_NEW = PROPOSITION_ID;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET INTERACTION_ID_NEW = INTERACTION_ID;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET PROPOSITION_ID_NEW = PROPOSITION_ID;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET INTERACTION_ID_NEW = INTERACTION_ID;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET PROPOSITION_ID_NEW = PROPOSITION_ID;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET INTERACTION_ID_NEW = INTERACTION_ID;
COMMIT;

ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD MODIFY (PROPOSITION_ID NULL);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD MODIFY (INTERACTION_ID NULL);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP MODIFY (PROPOSITION_ID NULL);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP MODIFY (INTERACTION_ID NULL);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG MODIFY (PROPOSITION_ID NULL);
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG MODIFY (INTERACTION_ID NULL);
COMMIT;

UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET PROPOSITION_ID = NULL;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET INTERACTION_ID = NULL;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET PROPOSITION_ID = NULL;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET INTERACTION_ID = NULL;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET PROPOSITION_ID = NULL;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET INTERACTION_ID = NULL;
COMMIT;

ALTER TABLE AC_CAMPAIGNOFFER_BLD MODIFY PROPOSITION_ID VARCHAR2 (255);
ALTER TABLE AC_CAMPAIGNOFFER_BLD MODIFY INTERACTION_ID VARCHAR2 (255);
ALTER TABLE AC_CAMPAIGNOFFER_SWP MODIFY PROPOSITION_ID VARCHAR2 (255);
ALTER TABLE AC_CAMPAIGNOFFER_SWP MODIFY INTERACTION_ID VARCHAR2 (255);
ALTER TABLE AC_CAMPAIGNOFFER_STG MODIFY PROPOSITION_ID VARCHAR2 (255);
ALTER TABLE AC_CAMPAIGNOFFER_STG MODIFY INTERACTION_ID VARCHAR2 (255);
COMMIT;

UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET PROPOSITION_ID = PROPOSITION_ID_NEW;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET INTERACTION_ID = INTERACTION_ID_NEW;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET PROPOSITION_ID = PROPOSITION_ID_NEW;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET INTERACTION_ID = INTERACTION_ID_NEW;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET PROPOSITION_ID = PROPOSITION_ID_NEW;
UPDATE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET INTERACTION_ID = INTERACTION_ID_NEW;
COMMIT;

ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET UNUSED COLUMN PROPOSITION_ID_NEW;
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD SET UNUSED COLUMN INTERACTION_ID_NEW;
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET UNUSED COLUMN PROPOSITION_ID_NEW;
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP SET UNUSED COLUMN INTERACTION_ID_NEW;
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET UNUSED COLUMN PROPOSITION_ID_NEW;
ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG SET UNUSED COLUMN INTERACTION_ID_NEW;
COMMIT;

/*==================*/
/* Action: ROLLBACK */
/*==================*/
--ROLLBACK DROP TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD;
--ROLLBACK DROP TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP;
--ROLLBACK DROP TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG;
--ROLLBACK ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_BLD_BKP_SEP2024 RENAME TO AC_CAMPAIGNOFFER_BLD;
--ROLLBACK ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_SWP_BKP_SEP2024 RENAME TO AC_CAMPAIGNOFFER_SWP;
--ROLLBACK ALTER TABLE ADOBE_ETL.AC_CAMPAIGNOFFER_STG_BKP_SEP2024 RENAME TO AC_CAMPAIGNOFFER_STG;
--ROLLBACK COMMIT;

