--liquibase formatted sql
--changeset josgeary:release_227.1.02_ODS_ADOBE_ETL_CONTACT_HIST_COMBINED_AC_MODIFY_COLUMN_DATATYPE_ROLLBACK.sql runAlways:false
--preconditions onFail:HALT onError:HALT

/*****************************************************************************************************************
*  File name:02_ODS_ADOBE_ETL_CONTACT_HIST_COMBINED_AC_MODIFY_COLUMN_DATATYPE_ROLLBACK.sql
*  Purpose: To modify column datatype.
*  Prerequisites:                                                            
*  1. Login as SYSTEM/SYS
*  History
*  When               Who                           What
*  09/23/2024         Capgemini                     Initial Draft		                                                     
******************************************************************************************************************/

/*===============================*/
/* Action: BACKUP the table      */
/*===============================*/

CREATE TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD;
CREATE TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP;
CREATE TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG;
COMMIT;

/*========================================*/
/* Action: Alter the column datatype      */
/*========================================*/

ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD ADD BROADLOG_ID_PK_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP ADD BROADLOG_ID_PK_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG ADD BROADLOG_ID_PK_NEW VARCHAR2(255);
COMMIT;

UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD SET BROADLOG_ID_PK_NEW = BROADLOG_ID_PK;
UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP SET BROADLOG_ID_PK_NEW = BROADLOG_ID_PK;
UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG SET BROADLOG_ID_PK_NEW = BROADLOG_ID_PK;
COMMIT;

ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD MODIFY (BROADLOG_ID_PK NULL);
ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP MODIFY (BROADLOG_ID_PK NULL);
ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG MODIFY (BROADLOG_ID_PK NULL);
COMMIT;

UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD SET BROADLOG_ID_PK = NULL;
UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP SET BROADLOG_ID_PK = NULL;
UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG SET BROADLOG_ID_PK = NULL;
COMMIT;

ALTER TABLE CONTACT_HIST_COMBINED_AC_BLD MODIFY BROADLOG_ID_PK VARCHAR2 (255);
ALTER TABLE CONTACT_HIST_COMBINED_AC_SWP MODIFY BROADLOG_ID_PK VARCHAR2 (255);
ALTER TABLE CONTACT_HIST_COMBINED_AC_STG MODIFY BROADLOG_ID_PK VARCHAR2 (255);
COMMIT;

UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD SET BROADLOG_ID_PK = BROADLOG_ID_PK_NEW;
UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP SET BROADLOG_ID_PK = BROADLOG_ID_PK_NEW;
UPDATE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG SET BROADLOG_ID_PK = BROADLOG_ID_PK_NEW;
COMMIT;

ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD SET UNUSED COLUMN BROADLOG_ID_PK_NEW;
ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP SET UNUSED COLUMN BROADLOG_ID_PK_NEW;
ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG SET UNUSED COLUMN BROADLOG_ID_PK_NEW;
COMMIT;

/*==================*/
/* Action: ROLLBACK */
/*==================*/
--ROLLBACK DROP TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD;
--ROLLBACK DROP TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP;
--ROLLBACK DROP TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG;
--ROLLBACK ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_BLD_BKP_SEP2024 RENAME TO CONTACT_HIST_COMBINED_AC_BLD;
--ROLLBACK ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_SWP_BKP_SEP2024 RENAME TO CONTACT_HIST_COMBINED_AC_SWP;
--ROLLBACK ALTER TABLE ADOBE_ETL.CONTACT_HIST_COMBINED_AC_STG_BKP_SEP2024 RENAME TO CONTACT_HIST_COMBINED_AC_STG;
--ROLLBACK COMMIT;

