--liquibase formatted sql
--changeset josgeary:release_227.1.03_ODS_ADOBE_ETL_SMS_INB_OUB_MODIFY_COLUMN_DATATYPE_ROLLBACK.sql runAlways:false
--preconditions onFail:HALT onError:HALT

/*****************************************************************************************************************
*  File name:03_ODS_ADOBE_ETL_SMS_INB_OUB_MODIFY_COLUMN_DATATYPE_ROLLBACK.sql
*  Purpose: To modify column datatype.
*  Prerequisites:                                                            
*  1. Login as SYSTEM/SYS
*  History
*  When               Who                           What
*  09/23/2024         Capgemini                     Initial Draft		                                                     
******************************************************************************************************************/

/*===============================*/
/* Action: BACKUP the table      */
/*===============================*/

CREATE TABLE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG;
CREATE TABLE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG_BKP_SEP2024 AS SELECT * FROM ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG;
COMMIT;

/*========================================*/
/* Action: Alter the column datatype      */
/*========================================*/

ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG ADD SESSION_BROADLOG_ID_NEW VARCHAR2(255);
ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG ADD OUTBOUND_BROADLOG_ID_NEW VARCHAR2(255);
COMMIT;

UPDATE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG SET SESSION_BROADLOG_ID_NEW = SESSION_BROADLOG_ID;
UPDATE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG SET OUTBOUND_BROADLOG_ID_NEW = OUTBOUND_BROADLOG_ID;
COMMIT;

UPDATE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG SET SESSION_BROADLOG_ID = NULL;
UPDATE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG SET OUTBOUND_BROADLOG_ID = NULL;
COMMIT;

ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG MODIFY SESSION_BROADLOG_ID VARCHAR2 (255);
ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG MODIFY OUTBOUND_BROADLOG_ID VARCHAR2 (255);
COMMIT;

UPDATE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG SET SESSION_BROADLOG_ID = SESSION_BROADLOG_ID_NEW;
UPDATE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG SET OUTBOUND_BROADLOG_ID = OUTBOUND_BROADLOG_ID_NEW;
COMMIT;

ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG SET UNUSED COLUMN SESSION_BROADLOG_ID_NEW;
ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG SET UNUSED COLUMN OUTBOUND_BROADLOG_ID_NEW;
COMMIT;

/*==================*/
/* Action: ROLLBACK */
/*==================*/
--ROLLBACK DROP TABLE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG;
--ROLLBACK DROP TABLE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG;
--ROLLBACK ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_INBOUND_STG_BKP_SEP2024 RENAME TO AC_SMSGATEWAY_INBOUND_STG;
--ROLLBACK ALTER TABLE ADOBE_ETL.AC_SMSGATEWAY_OUTBOUND_STG_BKP_SEP2024 RENAME TO AC_SMSGATEWAY_OUTBOUND_STG;
--ROLLBACK COMMIT;

